services:
  backend:
    build: .
    container_name: autoflex-backend
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16
    container_name: autoflex-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: autoflexdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5